[app/api] Tests: test_download, tests coverage check. (#183)
* test(Tests): Add coverage pytest's tool. Add assertation for expected total coverage. As first commit try to ovveride cached BaseSettings by fixture.

* Ignore VSCode

* test(Tests): Finish test_download. As the app doesn't have a route for local download, add a check for the file that exists.

* test(Tests): Fix linting

* test(Tests): Add envs to api-app-pr git action

* test(Tests): Move fixtures to separate files. Use already-built fixtures. file_id id no longer UUID.

* test(Tests): Add the detection and publishing report in PR of pytest's run

* test(Tests): :sparkles: Delete action for run test from .yaml. Add the bash script for run test. Add the bash script

* test(Tests): :memo: Change main .yaml file to include all needded actions

* test(Tests): :white_check_mark: Change the test behavior - it should run on every new commit push, to avoid pass linting and test errors inside PR.

* test(Tests): Kepp api/app/.coverage inside folder. Add munchify to files_uploader fixture

* test(Tests): Run tests only on push with defined paths

* test(Tests): Add pylint ignore for whole file

* test(Tests): Fix pylint. Find errors from latest commit.

Merged untested commit  [api, jungle3] implement auth0 and new sessions (#188)

diff --git a/.github/workflows/api-app-pr.yaml b/.github/workflows/api-app-pr.yaml
--- a/.github/workflows/api-app-pr.yaml
+++ b/.github/workflows/api-app-pr.yaml
@@ -1,7 +1,7 @@
 name: api/app tests
 
 on:
-  pull_request:
+  push:
     paths:
       - 'api/app/**'
 
@@ -12,13 +12,19 @@ defaults:
 jobs:
   api-app-ci:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      pull-requests: write
+      repository-projects: write
 
     env:
       SQL_URL: "sqlite:///${{ github.workspace }}/mythica.db"
       DATABASE_PATH: "${{ github.workspace }}/mythica.db"
       PYTHONPATH: "${{ github.workspace }}/api/app"
-      ENABLE_STORAGE: false
       UPLOAD_FOLDER_AUTO_CLEAN: false
+      LOCAL_STORAGE_PATH: /tmp/local_storage
+      USE_LOCAL_STORAGE: true
+      TEST_FAIL_RATE: 82
 
     steps:
       - name: Checkout repository
@@ -52,7 +58,32 @@ jobs:
       - name: Create Schema
         run: |
           poetry run alembic -n sqlite upgrade head
+          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
+
+      - uses: 8BitJonny/gh-get-current-pr@3.0.0
+        id: PR
 
       - name: Run tests
+        id: pytester-cov
         run: |
-          poetry run pytest .
+          chmod +x ./prepare_git_cov_table.sh
+          ./prepare_git_cov_table.sh
+        shell: bash
+        
+      - name: Comment table-result inside PR
+        uses: ./github_coverage/post_git_issue/
+        # pass user input as arguments
+        with:
+          title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+          token: ${{secrets.GITHUB_TOKEN}}
+          assignees: ${{github.actor}}
+          # labels: workflow-output-table
+          body: ${{ steps.pytester-cov.outputs.output-table }}
+          repo: ${{ github.repository }}
+          pull_number: ${{ steps.PR.outputs.number }}
+
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+          echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+          exit 1
